/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package doglcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class EstimatorData_t implements lcm.lcm.LCMEncodable
{
    public double pos[];
    public double vel[];
    public double lp_vel[];
 
    public EstimatorData_t()
    {
        pos = new double[3];
        vel = new double[3];
        lp_vel = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x424ec1c352028b2bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(doglcm.EstimatorData_t.class))
            return 0L;
 
        classes.add(doglcm.EstimatorData_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lp_vel[a]); 
        }
 
    }
 
    public EstimatorData_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public EstimatorData_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static doglcm.EstimatorData_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        doglcm.EstimatorData_t o = new doglcm.EstimatorData_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pos[a] = ins.readDouble();
        }
 
        this.vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.vel[a] = ins.readDouble();
        }
 
        this.lp_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lp_vel[a] = ins.readDouble();
        }
 
    }
 
    public doglcm.EstimatorData_t copy()
    {
        doglcm.EstimatorData_t outobj = new doglcm.EstimatorData_t();
        outobj.pos = new double[(int) 3];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 3); 
        outobj.vel = new double[(int) 3];
        System.arraycopy(this.vel, 0, outobj.vel, 0, 3); 
        outobj.lp_vel = new double[(int) 3];
        System.arraycopy(this.lp_vel, 0, outobj.lp_vel, 0, 3); 
        return outobj;
    }
 
}

