"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class EstimatorData_t(object):
    __slots__ = ["pos", "vel", "lp_vel"]

    __typenames__ = ["double", "double", "double"]

    __dimensions__ = [[3], [3], [3]]

    def __init__(self):
        self.pos = [ 0.0 for dim0 in range(3) ]
        self.vel = [ 0.0 for dim0 in range(3) ]
        self.lp_vel = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(EstimatorData_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.pos[:3]))
        buf.write(struct.pack('>3d', *self.vel[:3]))
        buf.write(struct.pack('>3d', *self.lp_vel[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != EstimatorData_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return EstimatorData_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = EstimatorData_t()
        self.pos = struct.unpack('>3d', buf.read(24))
        self.vel = struct.unpack('>3d', buf.read(24))
        self.lp_vel = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if EstimatorData_t in parents: return 0
        tmphash = (0x424ec1c352028b2b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if EstimatorData_t._packed_fingerprint is None:
            EstimatorData_t._packed_fingerprint = struct.pack(">Q", EstimatorData_t._get_hash_recursive([]))
        return EstimatorData_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", EstimatorData_t._get_packed_fingerprint())[0]

