"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class ImuData_t(object):
    __slots__ = ["quaternion", "rpy", "angular_velocity", "linear_accelerometer", "gps_pos", "gps_vel"]

    __typenames__ = ["double", "double", "double", "double", "double", "double"]

    __dimensions__ = [[4], [3], [3], [3], [3], [3]]

    def __init__(self):
        self.quaternion = [ 0.0 for dim0 in range(4) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.angular_velocity = [ 0.0 for dim0 in range(3) ]
        self.linear_accelerometer = [ 0.0 for dim0 in range(3) ]
        self.gps_pos = [ 0.0 for dim0 in range(3) ]
        self.gps_vel = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(ImuData_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4d', *self.quaternion[:4]))
        buf.write(struct.pack('>3d', *self.rpy[:3]))
        buf.write(struct.pack('>3d', *self.angular_velocity[:3]))
        buf.write(struct.pack('>3d', *self.linear_accelerometer[:3]))
        buf.write(struct.pack('>3d', *self.gps_pos[:3]))
        buf.write(struct.pack('>3d', *self.gps_vel[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ImuData_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ImuData_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ImuData_t()
        self.quaternion = struct.unpack('>4d', buf.read(32))
        self.rpy = struct.unpack('>3d', buf.read(24))
        self.angular_velocity = struct.unpack('>3d', buf.read(24))
        self.linear_accelerometer = struct.unpack('>3d', buf.read(24))
        self.gps_pos = struct.unpack('>3d', buf.read(24))
        self.gps_vel = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if ImuData_t in parents: return 0
        tmphash = (0xe37ccd754a6105c8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ImuData_t._packed_fingerprint is None:
            ImuData_t._packed_fingerprint = struct.pack(">Q", ImuData_t._get_hash_recursive([]))
        return ImuData_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ImuData_t._get_packed_fingerprint())[0]

