"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class JointData_t(object):
    __slots__ = ["joint_id", "mode", "T", "W", "Pos", "Temp"]

    __typenames__ = ["int8_t", "int8_t", "float", "float", "float", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.joint_id = 0
        self.mode = 0
        self.T = 0.0
        self.W = 0.0
        self.Pos = 0.0
        self.Temp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(JointData_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbfffi", self.joint_id, self.mode, self.T, self.W, self.Pos, self.Temp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != JointData_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return JointData_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = JointData_t()
        self.joint_id, self.mode, self.T, self.W, self.Pos, self.Temp = struct.unpack(">bbfffi", buf.read(18))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if JointData_t in parents: return 0
        tmphash = (0x61099eb4135175e4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if JointData_t._packed_fingerprint is None:
            JointData_t._packed_fingerprint = struct.pack(">Q", JointData_t._get_hash_recursive([]))
        return JointData_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", JointData_t._get_packed_fingerprint())[0]

