/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package doglcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class JointData_t implements lcm.lcm.LCMEncodable
{
    public byte joint_id;
    public byte mode;
    public float T;
    public float W;
    public float Pos;
    public int Temp;
 
    public JointData_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x61099eb4135175e4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(doglcm.JointData_t.class))
            return 0L;
 
        classes.add(doglcm.JointData_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.joint_id); 
 
        outs.writeByte(this.mode); 
 
        outs.writeFloat(this.T); 
 
        outs.writeFloat(this.W); 
 
        outs.writeFloat(this.Pos); 
 
        outs.writeInt(this.Temp); 
 
    }
 
    public JointData_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public JointData_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static doglcm.JointData_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        doglcm.JointData_t o = new doglcm.JointData_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.joint_id = ins.readByte();
 
        this.mode = ins.readByte();
 
        this.T = ins.readFloat();
 
        this.W = ins.readFloat();
 
        this.Pos = ins.readFloat();
 
        this.Temp = ins.readInt();
 
    }
 
    public doglcm.JointData_t copy()
    {
        doglcm.JointData_t outobj = new doglcm.JointData_t();
        outobj.joint_id = this.joint_id;
 
        outobj.mode = this.mode;
 
        outobj.T = this.T;
 
        outobj.W = this.W;
 
        outobj.Pos = this.Pos;
 
        outobj.Temp = this.Temp;
 
        return outobj;
    }
 
}

