"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import doglcm.JointCmd_t

class LegCmd_t(object):
    __slots__ = ["leg_id", "joint_cmd"]

    __typenames__ = ["int8_t", "doglcm.JointCmd_t"]

    __dimensions__ = [None, [3]]

    def __init__(self):
        self.leg_id = 0
        self.joint_cmd = [ doglcm.JointCmd_t() for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(LegCmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.leg_id))
        for i0 in range(3):
            assert self.joint_cmd[i0]._get_packed_fingerprint() == doglcm.JointCmd_t._get_packed_fingerprint()
            self.joint_cmd[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LegCmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LegCmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LegCmd_t()
        self.leg_id = struct.unpack(">b", buf.read(1))[0]
        self.joint_cmd = []
        for i0 in range(3):
            self.joint_cmd.append(doglcm.JointCmd_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if LegCmd_t in parents: return 0
        newparents = parents + [LegCmd_t]
        tmphash = (0xfce1595f03ce06e6+ doglcm.JointCmd_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LegCmd_t._packed_fingerprint is None:
            LegCmd_t._packed_fingerprint = struct.pack(">Q", LegCmd_t._get_hash_recursive([]))
        return LegCmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LegCmd_t._get_packed_fingerprint())[0]

