/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package doglcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class LegData_t implements lcm.lcm.LCMEncodable
{
    public byte leg_id;
    public doglcm.JointData_t joint_data[];
 
    public LegData_t()
    {
        joint_data = new doglcm.JointData_t[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1fb0915c32fa4c2cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(doglcm.LegData_t.class))
            return 0L;
 
        classes.add(doglcm.LegData_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + doglcm.JointData_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.leg_id); 
 
        for (int a = 0; a < 3; a++) {
            this.joint_data[a]._encodeRecursive(outs); 
        }
 
    }
 
    public LegData_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public LegData_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static doglcm.LegData_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        doglcm.LegData_t o = new doglcm.LegData_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.leg_id = ins.readByte();
 
        this.joint_data = new doglcm.JointData_t[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.joint_data[a] = doglcm.JointData_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public doglcm.LegData_t copy()
    {
        doglcm.LegData_t outobj = new doglcm.LegData_t();
        outobj.leg_id = this.leg_id;
 
        outobj.joint_data = new doglcm.JointData_t[(int) 3];
        for (int a = 0; a < 3; a++) {
            outobj.joint_data[a] = this.joint_data[a].copy();
        }
 
        return outobj;
    }
 
}

