"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import doglcm.JointData_t

class LegData_t(object):
    __slots__ = ["leg_id", "joint_data"]

    __typenames__ = ["int8_t", "doglcm.JointData_t"]

    __dimensions__ = [None, [3]]

    def __init__(self):
        self.leg_id = 0
        self.joint_data = [ doglcm.JointData_t() for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(LegData_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.leg_id))
        for i0 in range(3):
            assert self.joint_data[i0]._get_packed_fingerprint() == doglcm.JointData_t._get_packed_fingerprint()
            self.joint_data[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LegData_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LegData_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LegData_t()
        self.leg_id = struct.unpack(">b", buf.read(1))[0]
        self.joint_data = []
        for i0 in range(3):
            self.joint_data.append(doglcm.JointData_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if LegData_t in parents: return 0
        newparents = parents + [LegData_t]
        tmphash = (0x1fb0915c32fa4c2c+ doglcm.JointData_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LegData_t._packed_fingerprint is None:
            LegData_t._packed_fingerprint = struct.pack(">Q", LegData_t._get_hash_recursive([]))
        return LegData_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LegData_t._get_packed_fingerprint())[0]

