"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class MpcOutput_t(object):
    __slots__ = ["force"]

    __typenames__ = ["double"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.force = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(MpcOutput_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.force[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MpcOutput_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MpcOutput_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MpcOutput_t()
        self.force = struct.unpack('>12d', buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if MpcOutput_t in parents: return 0
        tmphash = (0x41518b9a665a25b6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MpcOutput_t._packed_fingerprint is None:
            MpcOutput_t._packed_fingerprint = struct.pack(">Q", MpcOutput_t._get_hash_recursive([]))
        return MpcOutput_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", MpcOutput_t._get_packed_fingerprint())[0]

