/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package doglcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class MpcOutput_t implements lcm.lcm.LCMEncodable
{
    public double force[];
 
    public MpcOutput_t()
    {
        force = new double[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x41518b9a665a25b6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(doglcm.MpcOutput_t.class))
            return 0L;
 
        classes.add(doglcm.MpcOutput_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.force[a]); 
        }
 
    }
 
    public MpcOutput_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public MpcOutput_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static doglcm.MpcOutput_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        doglcm.MpcOutput_t o = new doglcm.MpcOutput_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.force = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.force[a] = ins.readDouble();
        }
 
    }
 
    public doglcm.MpcOutput_t copy()
    {
        doglcm.MpcOutput_t outobj = new doglcm.MpcOutput_t();
        outobj.force = new double[(int) 12];
        System.arraycopy(this.force, 0, outobj.force, 0, 12); 
        return outobj;
    }
 
}

