"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class UserCmd_t(object):
    __slots__ = ["gait_type", "test_mode", "cmd_linear_velocity", "cmd_angular_velocity"]

    __typenames__ = ["int8_t", "int8_t", "double", "double"]

    __dimensions__ = [None, None, [3], [3]]

    def __init__(self):
        self.gait_type = 0
        self.test_mode = 0
        self.cmd_linear_velocity = [ 0.0 for dim0 in range(3) ]
        self.cmd_angular_velocity = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(UserCmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.gait_type, self.test_mode))
        buf.write(struct.pack('>3d', *self.cmd_linear_velocity[:3]))
        buf.write(struct.pack('>3d', *self.cmd_angular_velocity[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != UserCmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return UserCmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = UserCmd_t()
        self.gait_type, self.test_mode = struct.unpack(">bb", buf.read(2))
        self.cmd_linear_velocity = struct.unpack('>3d', buf.read(24))
        self.cmd_angular_velocity = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if UserCmd_t in parents: return 0
        tmphash = (0x91eb09e855b20ef) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if UserCmd_t._packed_fingerprint is None:
            UserCmd_t._packed_fingerprint = struct.pack(">Q", UserCmd_t._get_hash_recursive([]))
        return UserCmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", UserCmd_t._get_packed_fingerprint())[0]

