/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package doglcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class UserCmd_t implements lcm.lcm.LCMEncodable
{
    public byte gait_type;
    public byte test_mode;
    public double cmd_linear_velocity[];
    public double cmd_angular_velocity[];
 
    public UserCmd_t()
    {
        cmd_linear_velocity = new double[3];
        cmd_angular_velocity = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x091eb09e855b20efL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(doglcm.UserCmd_t.class))
            return 0L;
 
        classes.add(doglcm.UserCmd_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.gait_type); 
 
        outs.writeByte(this.test_mode); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.cmd_linear_velocity[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.cmd_angular_velocity[a]); 
        }
 
    }
 
    public UserCmd_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public UserCmd_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static doglcm.UserCmd_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        doglcm.UserCmd_t o = new doglcm.UserCmd_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.gait_type = ins.readByte();
 
        this.test_mode = ins.readByte();
 
        this.cmd_linear_velocity = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.cmd_linear_velocity[a] = ins.readDouble();
        }
 
        this.cmd_angular_velocity = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.cmd_angular_velocity[a] = ins.readDouble();
        }
 
    }
 
    public doglcm.UserCmd_t copy()
    {
        doglcm.UserCmd_t outobj = new doglcm.UserCmd_t();
        outobj.gait_type = this.gait_type;
 
        outobj.test_mode = this.test_mode;
 
        outobj.cmd_linear_velocity = new double[(int) 3];
        System.arraycopy(this.cmd_linear_velocity, 0, outobj.cmd_linear_velocity, 0, 3); 
        outobj.cmd_angular_velocity = new double[(int) 3];
        System.arraycopy(this.cmd_angular_velocity, 0, outobj.cmd_angular_velocity, 0, 3); 
        return outobj;
    }
 
}

